version: '3.8'

services:
  mailcatcher:
    image: schickling/mailcatcher
    container_name: mailcatcher
    ports:
      - "1080:1080" # Interfaz web
      - "1025:1025" # SMTP
    restart: unless-stopped